; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{46C4FB2A-841C-4501-8FF8-6F495A8D9234}
AppName=Tilem
AppVerName=Tilem v1.0
AppPublisher=2D Realms
AppPublisherURL=http://www.example.com/
AppSupportURL=http://www.example.com/
AppUpdatesURL=http://www.example.com/
DefaultDirName={pf}\Tilem
DefaultGroupName=Tilem
AllowNoIcons=yes
LicenseFile=C:\tilemPy\license.txt
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\tilemPy\dist\tilem.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\bz2.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\python26.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\select.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\unicodedata.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\w9xpopen.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wx._controls_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wx._core_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wx._gdi_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wx._misc_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wx._windows_.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wxbase28uh_net_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wxbase28uh_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wxmsw28uh_adv_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wxmsw28uh_core_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\tilemPy\dist\wxmsw28uh_html_vc.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Tilem"; Filename: "{app}\tilem.exe"
Name: "{commondesktop}\Tilem"; Filename: "{app}\tilem.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\tilem.exe"; Description: "{cm:LaunchProgram,Tilem}"; Flags: nowait postinstall skipifsilent



